// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNW6ZZ3tPwJ03WhLxqG21vbh6AfR7AuMQ',
    appId: '1:739087211490:web:c16478d716558a741ff7bb',
    messagingSenderId: '739087211490',
    projectId: 'onlinecoaching-e180a',
    authDomain: 'onlinecoaching-e180a.firebaseapp.com',
    storageBucket: 'onlinecoaching-e180a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJGiMOnIYQITbA3jWVNxjM7W4UrrV_yI',
    appId: '1:739087211490:android:a33296411b9973861ff7bb',
    messagingSenderId: '739087211490',
    projectId: 'onlinecoaching-e180a',
    storageBucket: 'onlinecoaching-e180a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByZVxsOfDW9-fH0J4CjgmpNQDTp5GAUKg',
    appId: '1:739087211490:ios:8e008d24af98464a1ff7bb',
    messagingSenderId: '739087211490',
    projectId: 'onlinecoaching-e180a',
    storageBucket: 'onlinecoaching-e180a.firebasestorage.app',
    iosBundleId: 'com.example.aliNasserOnlineCoachingApp',
  );
}
